- .gitignore
- package.json
- src/docula-options.ts
- src/docula-plugin.ts
- src/plugins/github.ts
- test/docula.test.ts
- test/plugins/github.test.ts
> GitHub plugin

- package.json
- src/docula-options.ts
- src/plugins/npm.ts
- test/plugins/github.test.ts
- test/plugins/npm.test.ts
> npm plugin

- bin/docula.js
- package.json
- src/eleventy.ts
> docula executable as module

- .gitignore
- package.json
> updating xo to 0.53.1

- init/docs/Readme.md
> add docs documentation

- package.json
upgrading typescript and jest to latest
> upgrading typescript and jest to latest

- package.json
> upgrading typescript to 4.9.5

- package.json
> upgrading node-fetch to 3.3.0

- package.json
upgrading markdown-it-anchor to 8.6.6
> upgrading markdown-it-anchor to 8.6.6

- package.json
upgrading instantsearch.js to 4.50.2
> upgrading instantsearch.js to 4.50.2

- package.json
> upgrading fs-extra to 11.1.0

- package.json
> upgrading dayjs to 1.11.7

- package.json
> upgrading commander to 10.0.0

- package.json
> upgrading axios to 1.3.0

- test/docula.test.ts
- test/mock/npm-downloads.json
- test/plugins/npm.test.ts
> mock axios for npm plugin

- init/_data/project.js
- init/_includes/assets/css/styles/algolia.css
- init/_includes/doc.njk
- init/_includes/search/algolia.njk
- init/_includes/shared/head.njk
- init/_includes/shared/main.njk
- init/_includes/shared/scripts.njk
- init/_includes/shared/searchEngine.njk
- init/_includes/shared/searchModal.njk
- init/index.njk
- init/search-index.md
- init/versions.njk
- src/docula.ts
- src/eleventy.ts
- src/eleventy/global-data.ts
- src/eleventy/globalData.ts
- src/eleventy/shortcodes.ts
- src/plugins/algolia.ts
- src/plugins/index.ts
- src/schemas.ts
- src/tools/__mocks__/inquirer-prompt.ts
- src/tools/inquirer-prompt.ts
- test/docula.test.ts
- test/eleventy.test.ts
- test/eleventy/shortcodes.test.ts
- test/plugins/algolia.test.ts
> add algolia plugin and refactor on plugin architecture

- src/plugins/algolia.ts
updating algolia plugin format
> updating algolia plugin format

- package.json
upgrading markdown-it-anchor to 8.6.7
> upgrading markdown-it-anchor to 8.6.7

- package.json
> upgrading jest to 29.4.3

- package.json
upgrading instantsearch.js to 4.51.1
> upgrading instantsearch.js to 4.51.1

- package.json
> upgrading axios to 1.3.4

- package.json
upgrading @types/express to 4.17.17
> upgrading @types/express to 4.17.17

- .github/workflows/release.yaml
- README.md
- package.json
> Adding in release workflow

- init/_includes/doc.njk
- init/_includes/shared/head.njk
- init/index.njk
- init/versions.njk
> add custom title in html tags

- package.json
- src/config.ts
> upgrade ajv to the last version

- test/docula.test.ts
> fix originPath on test

- test/config.test.ts
> fix config test

- site/_includes/assets/css/styles/home.css
> fix desktop site styles

- package.json
> upgrading luxon to 3.3.0

- package.json
- src/eleventy.ts
- test/eleventy.test.ts
- test/plugins/github.test.ts
upgrading lint and testing modules
> upgrading lint and testing modules

- package.json
> upgrading node-fetch to 3.3.1

- package.json
upgrading instantsearch.js to 4.54.1
> upgrading instantsearch.js to 4.54.1

- package.json
> upgrading axios to 1.4.0

- package.json
> upgrading xo to 0.54.2

- package.json
upgrading instandsearch.js to 4.56.0
> upgrading instandsearch.js to 4.56.0

- package.json
> upgrading inquirer to 9.2.5

- src/docula.ts
- src/tools/__mocks__/path.ts
- src/tools/path.ts
- test/docula.test.ts
- test/eleventy.test.ts
> fix create site if it doesn't exist

- package.json
> upgrading typescript to 5.1.3

- .github/workflows/tests.yaml
moving to nodejs version 16, 18, and 20 for tests
> moving to nodejs version 16, 18, and 20 for tests

- package.json
upgrading instantsearch.js to 4.56.2
> upgrading instantsearch.js to 4.56.2

- package.json
> upgrading inquirer to 9.2.7

- package.json
> upgrading dotenv to 16.3.1

- package.json
> upgrading dayjs to 1.11.8

- package.json
upgrading algoliasearch to 4.17.2
> upgrading algoliasearch to 4.17.2

- package.json
- src/config.ts
- src/eleventy.ts
- src/eleventy/filters.ts
- tsconfig.json
> upgrading xo to 0.55.0

- package.json
> upgrading jest to 29.6.1

- package.json
upgrading instant search to 4.56.5
> upgrading instant search to 4.56.5

- package.json
> upgrading dayjs to 1.11.9

- package.json
upgrading algoliasearch to 4.19.0
> upgrading algoliasearch to 4.19.0

- package.json
> upgrading commander to 11.0.0

- package.json
upgrading instantsearch.js to 4.56.7
> upgrading instantsearch.js to 4.56.7

- .gitignore
- package.json
- tsconfig.json
adding for yarn support and inline maps
> adding for yarn support and inline maps

- package.json
> upgrading xo to 0.56.0

- package.json
> upgrading node-fetch to 3.3.2

- package.json
> upgrading luxon to 3.4.0

- package.json
upgrading instantsearch.js to 4.56.9
> upgrading instantsearch.js to 4.56.9

- package.json
> upgrading inquirer to 9.2.10

- package.json
upgrading algoliasearch to 4.19.1
> upgrading algoliasearch to 4.19.1

- package.json
> upgrading typescript to 5.2.2

- package.json
> upgrading inquirer to 9.2.11

- package.json
> upgrading axios to 1.5.0

- package.json
> upgrading winston to ^3.11.0

- package.json
> upgrading webpack to 5.89.0

- package.json
upgrading instantsearch.js to 4.64.0
> upgrading instantsearch.js to 4.64.0

- package.json
> upgrading fs-extra to 11.2.0

- package.json
> upgrading inquirer to 9.2.12

- package.json
> upgrading ecto to 2.2.5

- package.json
> upgrading dayjs to 1.11.10

- package.json
> upgrading axios to 1.6.5

- package.json
upgrading markdown-it to 14.0.0
> upgrading markdown-it to 14.0.0

- test/docula.test.ts
adding in ports to serve commands
> adding in ports to serve commands

- package.json
removing ts-node as not required
> removing ts-node as not required

- package.json
upgrading typescript, webpack, and @types/node to latest
> upgrading typescript, webpack, and @types/node to latest

- package.json
> upgrading express to 4.18.3

- package.json
> upgrading axios to 1.6.8

- package.json
> upgrading vitest to 1.4.0

- package.json
> upgrading vitest to 1.5.0

- package.json
> upgrading express to 4.19.2

- package.json
> upgrading ecto to 3.0.3

- package.json
> upgrading ecto to 3.0.4

- package.json
> upgrading webpack to 5.92.0

- package.json
> upgrading ecto to 3.0.5

- package.json
> upgrading axios to 1.7.2

- src/builder.ts
fixing to use the main render section on ecto
> fixing to use the main render section on ecto

- .gitignore
- package.json
upgrading typescript and webpack to latest
> upgrading typescript and webpack to latest

- package.json
> upgrading ecto to 3.0.6

- package.json
> upgrading xo to 0.59.0

- package.json
upgrading update-notifier to 7.1.0
> upgrading update-notifier to 7.1.0

- template/css/base.css
- template/css/multipage.css
- template/docs.hbs
- template/includes/multipage/doc.hbs
- template/includes/multipage/hero.hbs
- template/includes/multipage/home.hbs
- template/includes/singlepage/content.hbs
- template/index.hbs
- template/releases.hbs
> fix: template indentation and styles

- package.json
> upgrading vitest to 2.0.5

- package.json
> updating axios to 1.7.3

- package.json
> upgrading ecto to 3.0.8

- package.json
upgrading update-notifier to 7.2.0
> upgrading update-notifier to 7.2.0

- package.json
- src/builder.ts
- template/css/base.css
- template/css/multipage.css
- template/includes/multipage/doc.hbs
- template/includes/multipage/scripts.hbs
- test/builder.test.ts
> feat: table of content

- package.json
> upgrading axios to 1.7.4

- .github/workflows/deploy-site.yml
- .gitignore
- package.json
- site/docula.config.cjs
- src/docula.ts
- test/fixtures/mega-page-site/docula.config.cjs
- test/fixtures/single-page-site-onprepare/docula.config.cjs
- vitest.config.mjs
fixing dist for site and updating docula serve console message
> fixing dist for site and updating docula serve console message

- .github/workflows/code-coverage.yaml
- .github/workflows/deploy-site.yml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
> adding in workflow_dispatch

- package.json
updating @types/node to latest
> updating @types/node to latest

- package.json
upgrading @types/node to 22.4.1
> upgrading @types/node to 22.4.1

- src/helpers.ts
moving to function calls with js-yaml
> moving to function calls with js-yaml

- package.json
upgrading webpack and typescript to lastest
> upgrading webpack and typescript to lastest

- package.json
- src/options.ts
> ESM and CJS support

- package.json
updating update-notifier to 7.3.1
> updating update-notifier to 7.3.1

- package.json
> upgrading axios to 1.7.7

- package.json
> upgrading keyv to 5.0.1

- package.json
> upgrading webpack to 5.95.0

- package.json
> upgrading vitest to 2.1.2

- package.json
- test/builder.test.ts
- test/docula.test.ts
- test/fixtures/single-page-site/README.md
> upgrading ecto to 4.1.2

- package.json
- src/docula.ts
- src/helpers.ts
- src/options.ts
- test/fixtures/no-front-matter.md
- test/helpers.test.ts
updating dependencies and removing js-yaml for writr
> updating dependencies and removing js-yaml for writr

- package.json
upgrading tsup and webpack to latest
> upgrading tsup and webpack to latest

- package.json
> upgrading vitest to 2.1.5

- package.json
> upgrading writr to 4.1.4

- .github/workflows/code-coverage.yaml
- .github/workflows/deploy-site.yml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
moving to pnpm for build process
> moving to pnpm for build process

- package.json
upgrading xo and typescript to latest
> upgrading xo and typescript to latest

- package.json
> upgrading writr to 4.2.0

- package.json
> upgrading ecto to 4.1.4

- package.json
> upgrading axios to 1.7.9

- package.json
- src/builder.ts
replacing gray-matter with writr
> replacing gray-matter with writr

- package.json
chore: upgrading writr to 4.3.0
> chore: upgrading writr to 4.3.0

- package.json
- src/docula.ts
feat: moving to serve handler for serve functionality
> feat: moving to serve handler for serve functionality

- package.json
chore: upgrading vitest to 3.0.6
> chore: upgrading vitest to 3.0.6

- package.json
chore: upgrading ecto to 4.2.0
> chore: upgrading ecto to 4.2.0

- package.json
chore: upgrading writr to 4.4.0
> chore: upgrading writr to 4.4.0

- test/builder.test.ts
chore - migrating fs.rmdir to fs.rm
> chore - migrating fs.rmdir to fs.rm

- package.json
chore: upgrading vitest to 3.0.9
> chore: upgrading vitest to 3.0.9

- package.json
chore: upgrading ecto to 4.2.1
> chore: upgrading ecto to 4.2.1

- .github/workflows/deploy-site.yml
- package.json
fix - fixing naming for site-build and site-serve to website:<action>
> fix - fixing naming for site-build and site-serve to website:<action>

- package.json
chore: upgrading axios to 1.8.4
> chore: upgrading axios to 1.8.4

- package.json
chore: upgrading writr to 4.4.2
> chore: upgrading writr to 4.4.2

- package.json
chore: upgrading ecto to 4.2.2
> chore: upgrading ecto to 4.2.2

- vitest.config.ts
feat: moving to vitest config in typescript
> feat: moving to vitest config in typescript

- package.json
fix: removing xo rule no longer in use
> fix: removing xo rule no longer in use

- package.json
chore: upgrading writr to 4.4.3
> chore: upgrading writr to 4.4.3

- .github/workflows/code-coverage.yaml
- .github/workflows/deploy-site.yml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
fix: updating actions to have permissions
> fix: updating actions to have permissions

- package.json
chore: upgrading tsup to 8.5.0
> chore: upgrading tsup to 8.5.0

- package.json
chore: upgrading docula to 3.1.3
> chore: upgrading docula to 3.1.3

- package.json
chore: upgrading ecto to 4.2.3
> chore: upgrading ecto to 4.2.3

- package.json
chore: upgrading axios to 1.9.0
> chore: upgrading axios to 1.9.0

- package.json
chore: upgrading feed to 5.0.1
> chore: upgrading feed to 5.0.1

- package.json
chore: upgrading ecto to 4.2.4
> chore: upgrading ecto to 4.2.4

- package.json
chore: upgrading ecto to 4.3.0
> chore: upgrading ecto to 4.3.0

- package.json
chore: upgrading webpack to 5.100.2
> chore: upgrading webpack to 5.100.2

- package.json
chore: upgrading ecto to 4.4.0
> chore: upgrading ecto to 4.4.0

- package.json
chore: upgrading dotenv to 17.2.0
> chore: upgrading dotenv to 17.2.0

- package.json
chore: upgrading axios to 1.12.2
> chore: upgrading axios to 1.12.2

- package.json
chore: upgrading writr to 4.5.0
> chore: upgrading writr to 4.5.0

- package.json
chore: upgrading dotenv to 17.2.2
> chore: upgrading dotenv to 17.2.2

- .gitignore
- test/github.test.ts
> fix: adding in test coverage

- package.json
- template/docs.hbs
- template/includes/singlepage/content.hbs
- template/index.hbs
- template/releases.hbs
fix: major fix to docs and ecto not rendering
> fix: major fix to docs and ecto not rendering
